# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /goinfre/ghan/webserv

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /goinfre/ghan/webserv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Users/ghan/.brew/Cellar/cmake/3.24.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /goinfre/ghan/webserv/CMakeFiles /goinfre/ghan/webserv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /goinfre/ghan/webserv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_webserv

# Build rule for target.
test_webserv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_webserv
.PHONY : test_webserv

# fast build rule for target.
test_webserv/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/build
.PHONY : test_webserv/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

srcs/ClientConnection.o: srcs/ClientConnection.cpp.o
.PHONY : srcs/ClientConnection.o

# target to build an object file
srcs/ClientConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/srcs/ClientConnection.cpp.o
.PHONY : srcs/ClientConnection.cpp.o

srcs/ClientConnection.i: srcs/ClientConnection.cpp.i
.PHONY : srcs/ClientConnection.i

# target to preprocess a source file
srcs/ClientConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/srcs/ClientConnection.cpp.i
.PHONY : srcs/ClientConnection.cpp.i

srcs/ClientConnection.s: srcs/ClientConnection.cpp.s
.PHONY : srcs/ClientConnection.s

# target to generate assembly for a file
srcs/ClientConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/srcs/ClientConnection.cpp.s
.PHONY : srcs/ClientConnection.cpp.s

srcs/Connection.o: srcs/Connection.cpp.o
.PHONY : srcs/Connection.o

# target to build an object file
srcs/Connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/Connection.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Connection.cpp.o
.PHONY : srcs/Connection.cpp.o

srcs/Connection.i: srcs/Connection.cpp.i
.PHONY : srcs/Connection.i

# target to preprocess a source file
srcs/Connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/Connection.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Connection.cpp.i
.PHONY : srcs/Connection.cpp.i

srcs/Connection.s: srcs/Connection.cpp.s
.PHONY : srcs/Connection.s

# target to generate assembly for a file
srcs/Connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/Connection.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Connection.cpp.s
.PHONY : srcs/Connection.cpp.s

srcs/HttpParser.o: srcs/HttpParser.cpp.o
.PHONY : srcs/HttpParser.o

# target to build an object file
srcs/HttpParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/HttpParser.cpp.o
.PHONY : srcs/HttpParser.cpp.o

srcs/HttpParser.i: srcs/HttpParser.cpp.i
.PHONY : srcs/HttpParser.i

# target to preprocess a source file
srcs/HttpParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/HttpParser.cpp.i
.PHONY : srcs/HttpParser.cpp.i

srcs/HttpParser.s: srcs/HttpParser.cpp.s
.PHONY : srcs/HttpParser.s

# target to generate assembly for a file
srcs/HttpParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/HttpParser.cpp.s
.PHONY : srcs/HttpParser.cpp.s

srcs/HttpServer.o: srcs/HttpServer.cpp.o
.PHONY : srcs/HttpServer.o

# target to build an object file
srcs/HttpServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/HttpServer.cpp.o
.PHONY : srcs/HttpServer.cpp.o

srcs/HttpServer.i: srcs/HttpServer.cpp.i
.PHONY : srcs/HttpServer.i

# target to preprocess a source file
srcs/HttpServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/HttpServer.cpp.i
.PHONY : srcs/HttpServer.cpp.i

srcs/HttpServer.s: srcs/HttpServer.cpp.s
.PHONY : srcs/HttpServer.s

# target to generate assembly for a file
srcs/HttpServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/HttpServer.cpp.s
.PHONY : srcs/HttpServer.cpp.s

srcs/PassiveSockets.o: srcs/PassiveSockets.cpp.o
.PHONY : srcs/PassiveSockets.o

# target to build an object file
srcs/PassiveSockets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/PassiveSockets.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/PassiveSockets.cpp.o
.PHONY : srcs/PassiveSockets.cpp.o

srcs/PassiveSockets.i: srcs/PassiveSockets.cpp.i
.PHONY : srcs/PassiveSockets.i

# target to preprocess a source file
srcs/PassiveSockets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/PassiveSockets.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/PassiveSockets.cpp.i
.PHONY : srcs/PassiveSockets.cpp.i

srcs/PassiveSockets.s: srcs/PassiveSockets.cpp.s
.PHONY : srcs/PassiveSockets.s

# target to generate assembly for a file
srcs/PassiveSockets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/PassiveSockets.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/PassiveSockets.cpp.s
.PHONY : srcs/PassiveSockets.cpp.s

srcs/UriParser.o: srcs/UriParser.cpp.o
.PHONY : srcs/UriParser.o

# target to build an object file
srcs/UriParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/UriParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/UriParser.cpp.o
.PHONY : srcs/UriParser.cpp.o

srcs/UriParser.i: srcs/UriParser.cpp.i
.PHONY : srcs/UriParser.i

# target to preprocess a source file
srcs/UriParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/UriParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/UriParser.cpp.i
.PHONY : srcs/UriParser.cpp.i

srcs/UriParser.s: srcs/UriParser.cpp.s
.PHONY : srcs/UriParser.s

# target to generate assembly for a file
srcs/UriParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/UriParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/UriParser.cpp.s
.PHONY : srcs/UriParser.cpp.s

srcs/Validator.o: srcs/Validator.cpp.o
.PHONY : srcs/Validator.o

# target to build an object file
srcs/Validator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/Validator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/srcs/Validator.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Validator.cpp.o
.PHONY : srcs/Validator.cpp.o

srcs/Validator.i: srcs/Validator.cpp.i
.PHONY : srcs/Validator.i

# target to preprocess a source file
srcs/Validator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/Validator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/srcs/Validator.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Validator.cpp.i
.PHONY : srcs/Validator.cpp.i

srcs/Validator.s: srcs/Validator.cpp.s
.PHONY : srcs/Validator.s

# target to generate assembly for a file
srcs/Validator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/srcs/Validator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/srcs/Validator.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/srcs/Validator.cpp.s
.PHONY : srcs/Validator.cpp.s

tests/test.o: tests/test.cpp.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

tests/test_client_io.o: tests/test_client_io.cpp.o
.PHONY : tests/test_client_io.o

# target to build an object file
tests/test_client_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/test_client_io.cpp.o
.PHONY : tests/test_client_io.cpp.o

tests/test_client_io.i: tests/test_client_io.cpp.i
.PHONY : tests/test_client_io.i

# target to preprocess a source file
tests/test_client_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/test_client_io.cpp.i
.PHONY : tests/test_client_io.cpp.i

tests/test_client_io.s: tests/test_client_io.cpp.s
.PHONY : tests/test_client_io.s

# target to generate assembly for a file
tests/test_client_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/tests/test_client_io.cpp.s
.PHONY : tests/test_client_io.cpp.s

tests/test_parser.o: tests/test_parser.cpp.o
.PHONY : tests/test_parser.o

# target to build an object file
tests/test_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_parser.cpp.o
.PHONY : tests/test_parser.cpp.o

tests/test_parser.i: tests/test_parser.cpp.i
.PHONY : tests/test_parser.i

# target to preprocess a source file
tests/test_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_parser.cpp.i
.PHONY : tests/test_parser.cpp.i

tests/test_parser.s: tests/test_parser.cpp.s
.PHONY : tests/test_parser.s

# target to generate assembly for a file
tests/test_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_parser.cpp.s
.PHONY : tests/test_parser.cpp.s

tests/test_server_io.o: tests/test_server_io.cpp.o
.PHONY : tests/test_server_io.o

# target to build an object file
tests/test_server_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tests/test_server_io.cpp.o
.PHONY : tests/test_server_io.cpp.o

tests/test_server_io.i: tests/test_server_io.cpp.i
.PHONY : tests/test_server_io.i

# target to preprocess a source file
tests/test_server_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tests/test_server_io.cpp.i
.PHONY : tests/test_server_io.cpp.i

tests/test_server_io.s: tests/test_server_io.cpp.s
.PHONY : tests/test_server_io.s

# target to generate assembly for a file
tests/test_server_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/tests/test_server_io.cpp.s
.PHONY : tests/test_server_io.cpp.s

tests/test_socket_generator.o: tests/test_socket_generator.cpp.o
.PHONY : tests/test_socket_generator.o

# target to build an object file
tests/test_socket_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_socket_generator.cpp.o
.PHONY : tests/test_socket_generator.cpp.o

tests/test_socket_generator.i: tests/test_socket_generator.cpp.i
.PHONY : tests/test_socket_generator.i

# target to preprocess a source file
tests/test_socket_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_socket_generator.cpp.i
.PHONY : tests/test_socket_generator.cpp.i

tests/test_socket_generator.s: tests/test_socket_generator.cpp.s
.PHONY : tests/test_socket_generator.s

# target to generate assembly for a file
tests/test_socket_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_socket_generator.cpp.s
.PHONY : tests/test_socket_generator.cpp.s

tests/test_validator.o: tests/test_validator.cpp.o
.PHONY : tests/test_validator.o

# target to build an object file
tests/test_validator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_validator.cpp.o
.PHONY : tests/test_validator.cpp.o

tests/test_validator.i: tests/test_validator.cpp.i
.PHONY : tests/test_validator.i

# target to preprocess a source file
tests/test_validator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_validator.cpp.i
.PHONY : tests/test_validator.cpp.i

tests/test_validator.s: tests/test_validator.cpp.s
.PHONY : tests/test_validator.s

# target to generate assembly for a file
tests/test_validator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_webserv.dir/build.make CMakeFiles/test_webserv.dir/tests/test_validator.cpp.s
.PHONY : tests/test_validator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... client"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... server"
	@echo "... test_webserv"
	@echo "... srcs/ClientConnection.o"
	@echo "... srcs/ClientConnection.i"
	@echo "... srcs/ClientConnection.s"
	@echo "... srcs/Connection.o"
	@echo "... srcs/Connection.i"
	@echo "... srcs/Connection.s"
	@echo "... srcs/HttpParser.o"
	@echo "... srcs/HttpParser.i"
	@echo "... srcs/HttpParser.s"
	@echo "... srcs/HttpServer.o"
	@echo "... srcs/HttpServer.i"
	@echo "... srcs/HttpServer.s"
	@echo "... srcs/PassiveSockets.o"
	@echo "... srcs/PassiveSockets.i"
	@echo "... srcs/PassiveSockets.s"
	@echo "... srcs/UriParser.o"
	@echo "... srcs/UriParser.i"
	@echo "... srcs/UriParser.s"
	@echo "... srcs/Validator.o"
	@echo "... srcs/Validator.i"
	@echo "... srcs/Validator.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_client_io.o"
	@echo "... tests/test_client_io.i"
	@echo "... tests/test_client_io.s"
	@echo "... tests/test_parser.o"
	@echo "... tests/test_parser.i"
	@echo "... tests/test_parser.s"
	@echo "... tests/test_server_io.o"
	@echo "... tests/test_server_io.i"
	@echo "... tests/test_server_io.s"
	@echo "... tests/test_socket_generator.o"
	@echo "... tests/test_socket_generator.i"
	@echo "... tests/test_socket_generator.s"
	@echo "... tests/test_validator.o"
	@echo "... tests/test_validator.i"
	@echo "... tests/test_validator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

